export default [
	'Can you come on Sunday evening',
	'Do you deliver on Sundays',
	'Have a nice day',
	'He quit school last week',
	'He watches TV every day',
	'How many days are there in a week',
	'How was your week',
	'I am leaving next week',
	'I cook almost every day',
	'I do that every week',
	"I don't go to school on Sunday",
	"I don't work on Sunday",
	'I exercise every day',
	'I go to church on Sunday',
	'I got sick last week',
	'I remember those days',
	'I run five miles a day',
	'I swim once a week',
	'I use it every day',
	'I was born on Monday',
	'I work every day except Sunday',
	'I work on Sunday',
	"I'm free on Sunday",
	'Is it open on Sunday',
	'It rained for a week',
	'It was a terrible day',
	'It was a very hot day',
	"It's a new day",
	'No one go to school on Sunday',
	'Saturday is the last day of the week',
	'See you next week',
	'Some keep fast on Thursday',
	'Sunday follows Saturday',
	'Sunday a is holiday',
	'Sunday is the first day of the week',
	'The day is almost over',
	'The first day of the week is Sunday',
	'The school is closed on Sundays',
	'The wind blew all day',
	'There are seven days in a week',
	'This happens every day',
	'Today is not your day',
	'Tomorrow is Sunday',
	'We never work on Sunday',
	"We'll meet on Sunday",
	'What a day',
	'What a terrible day',
	'What did you do last Sunday',
	'What do you do on Sundays',
	'Yesterday was Sunday'
];
